language: ruby
rvm:
  - 2.3
script:
  - CXX=g++-6 CC=gcc-6 bundle exec rake
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
before_install:
    - eval "${MATRIX_EVAL}"
